services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://chanyeeyoon_db_user:findanything@ac-dcnfyha-shard-00-00.1kbvxc3.mongodb.net:27017,ac-dcnfyha-shard-00-01.1kbvxc3.mongodb.net:27017,ac-dcnfyha-shard-00-02.1kbvxc3.mongodb.net:27017/?ssl=true&replicaSet=atlas-e8w7gs-shard-0&authSource=admin&appName=Cluster0
      - JWT_SECRET=xd123
      - CORS_ORIGIN=http://localhost:4000
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - find-anything-network
 
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000
      dockerfile: Dockerfile
      
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - find-anything-network
 
networks:
  find-anything-network:
    driver: bridge
 